# Generated by Django 5.2.7 on 2025-11-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='preparacion',
            new_name='descripcion',
        ),
    ]
