# Generated by Django 5.2.7 on 2025-11-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_rename_preparacion_receta_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='descripcion',
            new_name='instrucciones',
        ),
    ]
